name: Tests

on:
  push:
  pull_request:

jobs:
  neovim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Run Tests
        run: nvim --headless -u NONE -i NONE -n -c 'lua dofile("tests/run.lua")'
